# Generated by Django 5.2 on 2025-05-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_can_place_ads_user_can_place_bids_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Viewer', 'Viewer')], default='Staff', max_length=50, null=True),
        ),
    ]
