# Generated by Django 5.2 on 2025-07-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_subscription_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_tier',
        ),
    ]
