# Generated by Django 5.1.5 on 2025-08-26 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_contact_fields"),
        ("users", "0004_passwordresetotp"),
    ]

    operations = []
