# Generated by Django 5.1.5 on 2025-09-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_merge_0004_add_contact_fields_0004_passwordresetotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bank_country",
            field=models.CharField(
                default="SE",
                help_text="Bank country code for payment processing",
                max_length=2,
            ),
        ),
    ]
