# Generated by Django 5.1.5 on 2025-09-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_bank_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bank_account_holder",
            field=models.CharField(
                blank=True,
                help_text="Bank account holder name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_account_number",
            field=models.CharField(
                blank=True, help_text="Bank account number", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_currency",
            field=models.CharField(
                default="SEK",
                help_text="Bank currency for payment processing",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_routing_number",
            field=models.CharField(
                blank=True, help_text="Bank routing number", max_length=255, null=True
            ),
        ),
    ]
