# Generated by Django 5.1.5 on 2025-09-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_bank_account_holder_user_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="payout_frequency",
            field=models.CharField(
                default="weekly", help_text="Frequency of payouts", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="payout_method",
            field=models.CharField(
                default="bank_transfer", help_text="Method of payout", max_length=20
            ),
        ),
    ]
