version: "3.8"

services:
  web:
    build: .
    image: nordicloop-backend:1.0
    container_name: nordicloop-be
    ports:
      - 8002:8001
    env_file:
      - .env
    depends_on: 
      - db
    networks:
      - nordicloop-network

  db:
    image: postgres:17
    container_name: nordicloop-db
    env_file:
      - .env
    ports:
      - 5435:5432

    # command: ["postgres","-p","5437"]

    networks:
      - nordicloop-network


networks:
  nordicloop-network: