version: "3.8"

services:

  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - 5439:5432
    networks:
      - nordicloop-network
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    image: csrolivier/nordicloop-backend:1.0
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on: 
      - db
    networks:
      - nordicloop-network
    volumes:
      - ./media:/media


networks:
  nordicloop-network:
volumes:
  postgres_data: