# Generated by Django 5.2 on 2025-08-07 00:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Flexible Business Plans for Sustainable Growth', max_length=200)),
                ('subtitle', models.TextField(default="Flexible plans for every business; whether you're just starting or looking to scale sustainability.")),
                ('section_label', models.CharField(default='Pricing', max_length=50)),
                ('cta_text', models.CharField(default='Get Started', max_length=50)),
                ('cta_url', models.CharField(default='/coming-soon', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Page Content',
                'verbose_name_plural': 'Pricing Page Content',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Plan name (e.g., 'Free Plan')", max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly price in SEK (0 for free plan)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='SEK', max_length=3)),
                ('color', models.CharField(default='#008066', help_text='Hex color code for the plan', max_length=7)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular/recommended plan')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for selection')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.TextField(help_text='Description of the feature')),
                ('is_included', models.BooleanField(default=True, help_text='Whether this feature is included in the plan')),
                ('order', models.IntegerField(default=0, help_text='Display order within the plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pricing.pricingplan')),
            ],
            options={
                'verbose_name': 'Pricing Feature',
                'verbose_name_plural': 'Pricing Features',
                'ordering': ['order'],
            },
        ),
    ]
