# Generated by Django 5.2 on 2025-08-07 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for the feature', max_length=100)),
                ('category', models.CharField(choices=[('marketplace', 'Marketplace'), ('auctions', 'Auctions'), ('reporting', 'Reporting'), ('support', 'Support'), ('commission', 'Commission'), ('verification', 'Verification'), ('access', 'Access'), ('community', 'Community')], help_text='Feature category', max_length=20)),
                ('base_description', models.TextField(help_text='Base description template (can use placeholders)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this feature is available')),
                ('order', models.IntegerField(default=0, help_text='Global display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base Feature',
                'verbose_name_plural': 'Base Features',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included', models.BooleanField(default=True, help_text='Whether this feature is included in the plan')),
                ('custom_description', models.TextField(blank=True, help_text='Custom description for this plan (overrides base)', null=True)),
                ('feature_value', models.CharField(blank=True, help_text="Specific value for this plan (e.g., 'Unlimited', '9%', 'Limited')", max_length=100, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within the plan')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Highlight this feature as a key benefit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='pricing.basefeature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='pricing.pricingplan')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'ordering': ['order'],
                'unique_together': {('plan', 'base_feature')},
            },
        ),
        migrations.DeleteModel(
            name='PricingFeature',
        ),
    ]
