# Generated by Django 5.2 on 2025-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_selling_type_ad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price_per_partition',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='selling_type',
            field=models.CharField(choices=[('partition', 'Selling in Partition'), ('whole', 'Selling as Whole'), ('both', 'selling as whole and partion')], default='whole', max_length=20, null=True),
        ),
    ]
