# Generated by Django 5.2 on 2025-05-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_price_per_partition_alter_ad_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='selling_type',
            field=models.CharField(choices=[('partition', 'Selling in Partition'), ('whole', 'Selling as Whole'), ('both whole and partion', 'selling as whole and partion')], default='whole', max_length=255, null=True),
        ),
    ]
