# Generated by Django 5.2 on 2025-06-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_custom_auction_duration_alter_ad_auction_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='unit_of_measurement',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('tons', 'Tons'), ('tonnes', 'Tonnes'), ('lbs', 'Pounds'), ('pounds', 'Pounds'), ('pieces', 'Pieces'), ('units', 'Units'), ('bales', 'Bales'), ('containers', 'Containers'), ('m³', 'Cubic Meters'), ('cubic_meters', 'Cubic Meters'), ('liters', 'Liters'), ('gallons', 'Gallons'), ('meters', 'Meters')], default='tons', max_length=15),
        ),
    ]
