# Generated by Django 4.2.21 on 2025-06-04 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_categoryspecification'),
        ('ads', '0004_alter_ad_selling_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='country_of_origin',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='price_per_partition',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='selling_type',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='volume',
        ),
        migrations.AddField(
            model_name='ad',
            name='additives',
            field=models.CharField(blank=True, choices=[('UV Stabilizer', 'UV Stabilizer'), ('Antioxidant', 'Antioxidant'), ('Flame retardants', 'Flame retardants'), ('Chlorides', 'Chlorides'), ('NO additives', 'No additives')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='contamination',
            field=models.CharField(blank=True, choices=[('Clean', 'Clean'), ('Slightly contaminated', 'Slightly contaminated'), ('Heavily contaminated', 'Heavily contaminated')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='delivery',
            field=models.CharField(blank=True, choices=[('Pickup only', 'Pickup only'), ('Local Delivery', 'Local DElivery'), ('National shipping', 'National Shipping'), ('International Shipping', 'International Shipping'), ('Freight Forwarding', 'Freight Forwarding')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='material_frequency',
            field=models.CharField(blank=True, choices=[('one_time', 'One Time'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='origin',
            field=models.CharField(blank=True, choices=[('Post-industrial', 'Post-industrial'), ('Post-consumer', 'Post-consumer'), ('Mix', 'Mix')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='processing_methods',
            field=models.CharField(blank=True, choices=[('Blow moulding', 'Blow moulding'), ('Injection moulding', 'Injection moulding'), ('Extruion', 'Extrusion'), ('Calendering', 'Calenderng'), ('Rotational moulding', 'Rotation moulding'), ('Sintering', 'Sintering'), ('Thermoforming', 'Thermoforming')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='specification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.categoryspecification'),
        ),
        migrations.AddField(
            model_name='ad',
            name='storage',
            field=models.CharField(blank=True, choices=[('Climate Controlled', 'Climate Controlleld'), ('Protected Outdoor', 'Protected Outdoor'), ('Unprotected Outdoor', 'Uprotected Outdoor')], max_length=255, null=True),
        ),
    ]
