# Generated by Django 5.2 on 2025-06-11 08:57

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='material_image',
            field=base.fields.FirebaseImageField(blank=True, folder='material_images', max_length=500, null=True),
        ),
    ]
