# Generated by Django 5.2 on 2025-06-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_ad_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='status',
        ),
    ]
