# Generated by Django 5.2 on 2025-07-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_remove_ad_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payment_method',
        ),
    ]
