# Generated by Django 5.2 on 2025-07-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_alter_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended by Admin')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='suspended_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
