# Generated by Django 5.2 on 2025-08-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_add_completed_status'),
        ('ads', '0013_add_broker_fields'),
    ]

    operations = [
    ]
