# Generated by Django 5.1.5 on 2025-09-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0014_merge_20250820_1425"),
        ("company", "0007_alter_company_stripe_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="cancel_at_period_end",
            field=models.BooleanField(
                default=False, help_text="Cancel subscription at end of current period"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="next_billing_date",
            field=models.DateField(
                blank=True, help_text="Next billing date from Stripe", null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, help_text="Stripe Customer ID", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Price ID used for this subscription",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Subscription ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_end",
            field=models.DateTimeField(
                blank=True, help_text="Trial period end date if applicable", null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="last_payment",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("payment_failed", "Payment Failed"),
                    ("canceled", "Canceled"),
                    ("past_due", "Past Due"),
                    ("unpaid", "Unpaid"),
                    ("incomplete", "Incomplete"),
                    ("trialing", "Trialing"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("company",)},
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_customer_id"], name="ads_subscri_stripe__6085e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_subscription_id"], name="ads_subscri_stripe__eaa308_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="ads_subscri_status_0fe81c_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["plan"], name="ads_subscri_plan_4b6dd8_idx"),
        ),
    ]
