# Generated by Django 5.1.5 on 2025-09-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0015_add_stripe_fields_to_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="step_1_complete",
            field=models.BooleanField(
                default=False, help_text="Material Type step completion"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="step_2_complete",
            field=models.BooleanField(
                default=False, help_text="Specifications step completion"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="step_3_complete",
            field=models.BooleanField(
                default=False, help_text="Material Origin step completion"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="step_4_complete",
            field=models.BooleanField(
                default=False, help_text="Contamination step completion"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="step_5_complete",
            field=models.BooleanField(
                default=False, help_text="Processing Method step completion"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="step_6_complete",
            field=models.BooleanField(
                default=False, help_text="Location & Logistics step completion"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="step_7_complete",
            field=models.BooleanField(
                default=False, help_text="Quantity & Price step completion"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="step_8_complete",
            field=models.BooleanField(
                default=False, help_text="Title & Description step completion"
            ),
        ),
    ]
