# Generated by Django 5.1.5 on 2025-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0016_add_step_completion_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended by Admin"),
                    ("completed", "Completed"),
                    ("Draft", "Draft"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
