# Generated by Django 5.1.5 on 2025-09-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0017_alter_ad_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="ad",
            name="suspended_by_admin",
        ),
        migrations.AlterField(
            model_name="ad",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended by Admin"),
                    ("completed", "Completed"),
                    ("draft", "Draft"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
