# Generated by Django 5.1.5 on 2025-09-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0018_remove_is_active_and_suspended_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="pickup_available",
        ),
    ]
