# Generated by Django 5.1.5 on 2025-10-01 19:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0019_remove_pickup_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="available_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Total quantity available for auction",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="minimum_order_quantity",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Minimum quantity buyers must purchase (0 for no minimum)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="reserve_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="If no bids reach this price, the auction will not complete",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="starting_bid_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Initial bid price per unit",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
