# Generated by Django 5.1.5 on 2025-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0020_alter_ad_available_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="unit_of_measurement",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogram"),
                    ("ton", "Tons"),
                    ("tonne", "Tonnes"),
                    ("lb", "Pounds"),
                    ("pound", "Pounds"),
                    ("piece", "Pieces"),
                    ("unit", "Units"),
                    ("bale", "Bales"),
                    ("container", "Containers"),
                    ("m³", "Cubic Meters"),
                    ("cubic meter", "Cubic Meters"),
                    ("liter", "Liters"),
                    ("gallon", "Gallons"),
                    ("meter", "Meters"),
                ],
                default="tons",
                max_length=15,
            ),
        ),
    ]
