# Generated by Django 5.2 on 2025-04-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_handle_null_company_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='noreply@example.com', help_text='Company email for communications', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
