# Generated by Django 5.2 on 2025-04-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_company_user_alter_company_email_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(blank=True, help_text='Temporary storage for registration password', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(help_text='This email will be used for login after approval', max_length=254, unique=True),
        ),
    ]
