# Generated by Django 4.2.21 on 2025-06-04 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Natural/Clear', 'Natural/Clear'), ('White', 'White'), ('Black', 'Black'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Mixed Colors', 'Mixed Colors'), ('Custom Color', 'Custom Color')], max_length=50, null=True)),
                ('material_grade', models.CharField(blank=True, max_length=255, null=True)),
                ('material_form', models.CharField(blank=True, max_length=255, null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
