# Generated by Django 5.2 on 2025-05-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_alter_bid_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
