# Generated by Django 5.1.5 on 2025-08-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0002_add_paid_status"),
        ("bids", "0003_bidhistory_alter_bid_options_and_more"),
    ]

    operations = []
