# Generated by Django 5.2 on 2025-05-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_bid_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('Outbid', 'Outbid'), ('Highest_bid', 'Highest_bid')], default='Highest_bid', max_length=20, null=True),
        ),
    ]
