# Generated by Django 5.1.5 on 2025-08-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0004_merge_20250821_0847"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="authorization_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount authorized for this bid",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="authorization_created_at",
            field=models.DateTimeField(
                blank=True, help_text="When authorization was created", null=True
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="authorization_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When authorization expires (typically 7 days)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="authorization_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Authorization"),
                    ("authorized", "Authorized"),
                    ("captured", "Captured"),
                    ("canceled", "Canceled"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of payment authorization",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe payment intent ID for authorization hold",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="stripe_payment_method_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe payment method ID for pre-authorization",
                max_length=255,
                null=True,
            ),
        ),
    ]
