# Generated by Django 5.2 on 2025-05-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='current_Highest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
