# Generated by Django 5.1.5 on 2025-09-12 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0005_bid_authorization_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="authorization_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount authorized for this bid (calculated from integer fields)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="bid_price_per_unit",
            field=models.IntegerField(
                help_text="Bid price per unit of material (integer only)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="max_auto_bid_price",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum price for auto-bidding (integer only)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="volume_requested",
            field=models.IntegerField(
                help_text="Quantity of material requested (integer only)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="bidhistory",
            name="new_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="bidhistory",
            name="new_volume",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="bidhistory",
            name="previous_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bidhistory",
            name="previous_volume",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
