# Generated by Django 5.1.5 on 2025-09-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0006_alter_bid_authorization_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="stripe_transfer_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe transfer ID when funds are sent to seller",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="transfer_completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When transfer to seller was completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="transfer_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Transfer"),
                    ("completed", "Transfer Completed"),
                    ("failed", "Transfer Failed"),
                ],
                default="pending",
                help_text="Status of transfer to seller",
                max_length=20,
            ),
        ),
    ]
