# Generated by Django 5.2 on 2025-05-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_position',
        ),
        migrations.AddField(
            model_name='company',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(choices=[('manufacturing  & Production', 'Manufacturing & Production'), ('construction', 'Construction & Demolition'), ('retail', 'Wholesale & Retail'), ('packaging', 'Packaging & Printing'), ('recycling', 'Recycling & Waste Management'), ('Energy & Utilities', 'Energy & Utilities'), ('Other', 'Other')], default='manufacturing  & Production', max_length=255),
        ),
    ]
