# Generated by Django 5.2 on 2025-06-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
    ]
