# Generated by Django 5.2 on 2025-07-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_remove_company_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="primary_email",
        ),
        migrations.RemoveField(
            model_name="company",
            name="primary_first_name",
        ),
        migrations.RemoveField(
            model_name="company",
            name="primary_last_name",
        ),
        migrations.RemoveField(
            model_name="company",
            name="primary_position",
        ),
        migrations.RemoveField(
            model_name="company",
            name="secondary_email",
        ),
        migrations.RemoveField(
            model_name="company",
            name="secondary_first_name",
        ),
        migrations.RemoveField(
            model_name="company",
            name="secondary_last_name",
        ),
        migrations.RemoveField(
            model_name="company",
            name="secondary_position",
        ),
    ]
