# Generated by Django 5.1.5 on 2025-09-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_add_broker_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="last_payment_check",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time payment readiness was verified",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="payment_ready",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether company can receive payments",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="stripe_account_id",
            field=models.CharField(
                blank=True, help_text="Stripe Connect account ID", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="stripe_capabilities_complete",
            field=models.BooleanField(
                default=False,
                help_text="Whether Stripe account has required capabilities",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="stripe_onboarding_complete",
            field=models.BooleanField(
                default=False, help_text="Whether Stripe onboarding is complete"
            ),
        ),
    ]
