# Generated by Django 5.1.5 on 2025-09-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_company_last_payment_check_company_payment_ready_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="stripe_account_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Connect account ID",
                max_length=255,
                null=True,
            ),
        ),
    ]
