# Generated by Django 5.2 on 2025-07-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_target_subscription_tiers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='target_subscription_tiers',
        ),
    ]
